/* ==========================================================================
   Touris 知途 · 景点配图（由 tools/fetch-images.js 生成，请勿手改）

   全部图片已下载到 img/，运行时只读本地文件，不依赖任何外部服务。
   原始 Commons 地址与署名见 tools/image-sources.json 与 img/CREDITS.md。
   要重新下载：node tools/fetch-images.js
   ========================================================================== */

const SPOT_IMG = {
  "798艺术区":  'img/Beijing_798_Art_District.jpg',
  "北海公园":      'img/Beijing_Beihai_park_Qionghua-Insel_Tor-20110104-RM-141208.jpg',
  "城隍庙":        'img/Shanghai_-_Yu_Garden_-_0035.jpg',
  "出町柳桝形商店街": 'img/Demachiyanagi_station_building_20221008.jpg',
  "嵯峨野":        'img/Arashiyama_Part_II_-_Arashiyama7534.jpg',
  "大栅栏":        'img/Beijing_Qianmen_Street_-_panoramio.jpg',
  "东寺":          'img/Toji_2015.jpg',
  "渡月桥":        'img/Togetsukyo_in_Kyoto_Arashiyama.jpg',
  "二年坂三年坂":  'img/Sannenzaka_street_Kyoto_3811257874.jpg',
  "二条城":        'img/NinomaruPalace.jpg',
  "伏见稻荷大社":  'img/Torii_path_with_lantern_at_Fushimi_Inari_Taisha_Shrine_Kyoto_Japan.jpg',
  "鼓楼":          'img/The_Drum_Tower_of_Beijing.jpg',
  "故宫博物院":    'img/Sunset_of_the_Forbidden_City_2006.jpg',
  "国家博物馆":    'img/National_Museum_of_China_building_wide.jpg',
  "金阁寺":        'img/Golden_Pavilion_Kinkaku-ji_water_mirror_2024.jpg',
  "锦市场":        'img/Nishiki_Ichiba_by_matsuyuki.jpg',
  "京都国立博物馆": 'img/260214_Kyoto_National_Museum_Kyoto_Japan04bs4.jpg',
  "京都塔":        'img/commons-2af180c0.jpg',
  "京都站":        'img/Kyoto-STA_Central.jpg',
  "京都站伊势丹":  'img/Kyoto-STA_Central.jpg',
  "景山公园":      'img/Forbidden_City_from_Jingshan_Park_6349214639.jpg',
  "岚山竹林":      'img/2021_Sagano_Bamboo_forest_in_Arashiyama_Kyoto_Japan.jpg',
  "亮马河":        'img/Liangma_River_at_Xinyuan_St_20200808164518.jpg',
  "龙安寺":        'img/Kare-sansui_zen_garden_Ryo_an-ji_Kyoto_20190416_1.jpg',
  "陆家嘴":        'img/Pudong_Shanghai_November_2017_panorama.jpg',
  "慕田峪长城":    'img/Great_Wall_of_China_July_2006.jpg',
  "南禅寺":        'img/251213_Nanzen-ji_Kyoto_Japan01s3.jpg',
  "南京东路":      'img/20090705_Shanghai_Nanjing_Road_0602.jpg',
  "南锣鼓巷":      'img/Beijing_Nanluoguxiang_-_panoramio.jpg',
  "平安神宫":      'img/Heian-jingu_daigokuden.jpg',
  "祇园花见小路":  'img/150124_Gion_Kyoto_Japan01s3.jpg',
  "前门大街":      'img/Beijing_Qianmen_Street_-_panoramio.jpg',
  "清水寺":        'img/Kiyomizu.jpg',
  "三里屯":        'img/SOHO.jpg',
  "三十三间堂":    'img/Sanjusangendo_2022.jpg',
  "上海博物馆":    'img/Shanghai_Museum_exterior_1.jpg',
  "上海中心":      'img/Pudong_Shanghai_November_2017_panorama.jpg',
  "天安门广场":    'img/Tiananmen_Square_5283031153.jpg',
  "天龙寺":        'img/Tenryuji_Kyoto.jpg',
  "外滩":          'img/Pudong_Shanghai_November_2017_panorama.jpg',
  "西阵":          'img/Kyoto_Nishijin_Textile_show.jpg',
  "先斗町":        'img/Pontocho_by_Wolfiewolf_in_Nabeyacho_Kyoto.jpg',
  "鸭川河畔":      'img/Kamogawa_sakura.jpg',
  "颐和园":        'img/Longevity_Hill_of_the_Summer_Palace.jpg',
  "银阁寺":        'img/Ginkakuji_Kyoto03-r.jpg',
  "雍和宫":        'img/Peking_Jonghe_Tempel_-20071022-RM-094926.jpg',
  "豫园":          'img/Shanghai_-_Yu_Garden_-_0035.jpg',
  "圆明园":        'img/commons-725bf73d.jpg',
  "哲学之道":      'img/Japan_Kyoto_philosophers_walk_DSC00297.jpg',
};
